export const AUTH_SIGN_UP = 'AUTH_SIGN_UP';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT';
export const AUTH_SIGN_IN = 'AUTH_SIGN_IN';

export const BOARD_ACTION_TYPES = {
    POST: 'POST',
    PUT:'PUT',
    GET: 'GET',
    DELETE: 'DELETE'
}

export const BOARD_GET_EVENT = 'BOARD_GET_EVENT';
export const BOARD_GET_NOTICE = 'BOARD_GET_NOTICE';
export const BOARD_GET_MEETING = 'BOARD_GET_MEETING';
export const BOARD_GET_RANDOM = 'BOARD_GET_RANDOM';

export const BOARD_POST_EVENT = 'BOARD_POST_EVENT';
export const BOARD_POST_NOTICE = 'BOARD_POST_NOTICE';
export const BOARD_POST_MEETING = 'BOARD_POST_MEETING';
export const BOARD_POST_RANDOM = 'BOARD_POST_RANDOM';

export const BOARD_PUT_EVENT = 'BOARD_PUT_EVENT';
export const BOARD_PUT_NOTICE = 'BOARD_PUT_NOTICE';
export const BOARD_PUT_MEETING = 'BOARD_PUT_MEETING';
export const BOARD_PUT_RANDOM = 'BOARD_PUT_RANDOM';

export const BOARD_DEL_EVENT = 'BOARD_DEL_EVENT';
export const BOARD_DEL_NOTICE = 'BOARD_DEL_NOTICE';
export const BOARD_DEL_MEETING = 'BOARD_DEL_MEETING';
export const BOARD_DEL_RANDOM = 'BOARD_DEL_RANDOM';