export const AUTH_SIGN_UP = 'AUTH_SIGN_UP';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT';
export const AUTH_SIGN_IN = 'AUTH_SIGN_IN';
export const BOARD_GET_EVENT = 'BOARD_GET_EVENT';
export const BOARD_GET_NOTICE = 'BOARD_GET_NOTICE';
export const BOARD_GET_MEETING = 'BOARD_GET_MEETING';
export const BOARD_GET_RANDOM = 'BOARD_GET_RANDOM';