export const BOARD_TYPE = {
  MEETING: 'MEETING',
  NOTICE: 'NOTICE',
  EVENT: 'EVENT',
  DISCUSSION: 'DISCUSSION',
};

export const BOARD_PROPERTY = {
  PAGE_SIZE: 10,
  PAGINATION_SIZE: 5,
};

export const MEMBER_PROPERTY = {
  PAGE_SIZE: 10,
  PAGINATION_SIZE: 5
};