export const BOARD_TYPE = {
    MEETING: 'MEETING',
    NOTICE: 'NOTICE',
    EVENT: 'EVENT',
    FREECHAT: 'FREECHAT',
};

export const BOARD_PROPERTY = {
    ITEM_PER_PAGE: 10,
    PAGINATION_PER_PAGE: 5,
}